apiVersion: v1
kind: ConfigMap
metadata:
  name: db-schema
data:
  schema.sql: |
    CREATE SCHEMA file_queue_schema;
    CREATE USER file_queue_user WITH PASSWORD '${FILE_QUEUE_USER_PASSWORD}';
    GRANT USAGE ON SCHEMA file_queue_schema TO file_queue_user;
    GRANT CREATE, CONNECT ON DATABASE ${DB_NAME} TO file_queue_user;
    CREATE TABLE file_queue_schema.file_queue
    (
        id        SERIAL PRIMARY KEY,
        file_name VARCHAR NOT NULL
    );

    CREATE SCHEMA config_schema;
    CREATE USER config_user WITH PASSWORD '${CONFIG_USER_PASSWORD}';
    GRANT USAGE ON SCHEMA config_schema TO config_user;
    GRANT CREATE, CONNECT ON DATABASE ${DB_NAME} TO config_user;
    CREATE TABLE config_schema.config
    (
        id          SERIAL PRIMARY KEY,
        config_name VARCHAR NOT NULL,
        value       JSON    NOT NULL
    );
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-schema-migrate
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: "{{ .Values.postgresqlSchema.image }}"
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: root_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: root_user
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: host
            - name: FILE_QUEUE_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: file_queue_user_password
            - name: CONFIG_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: config_user_password
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              envsubst < /schema/schema.sql > /schema/rendered.sql && \
              psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -f /schema/rendered.sql
          volumeMounts:
            - name: schema
              mountPath: /schema
      restartPolicy: OnFailure
      volumes:
        - name: schema
          configMap:
            name: db-schema